version: "3.3"
networks:
  default:
    external:
      name: int371-network
services:
  db:
    image: postgres:10-alpine
    container_name: db_namjai
    restart: always
    volumes:
      - ./postgress:/var/lib/postgress
      - ./data-init.sql:/data-init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=namjai
