version: "3.3"
services:
  db:
    image: postgres:10-alpine
    container_name: db-namjai
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=namjai
