version: '3.3'
services:
  db:
    image: "postgres:10-alpine"
    container_name: db-namjai-service
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=namjai